CREATE TABLE skills (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    agent_id INTEGER REFERENCES users(id) not null,
    skill_id INTEGER REFERENCES skills_description(id) not null,
    level INTEGER
);
