CREATE TABLE items (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    agent_id INTEGER REFERENCES users(id) not null,
    item_id INTEGER REFERENCES items_description(id) not null,
    quantity INTEGER
);
